import './globals.css'

import { NextUIProvider } from '@nextui-org/react'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { ToastContainer } from 'react-toastify'

import Auth from '../components/Auth'
import ReduxProvider from '../components/ReduxProvider'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={nunito.className}>
				<ToastContainer />

				<ReduxProvider>
					<NextUIProvider>
						<Auth>{children}</Auth>
					</NextUIProvider>
				</ReduxProvider>
			</body>
		</html>
	)
}
